export * from '../containers/Home'
export * from '../containers/Products'
export * from '../containers/Cart'
export * from '../containers/SingUP'
export * from '../containers/login'
export * from '../containers/Admin'
